data_r <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?")
data_s <- subset(data_r, Date %in% c("1/2/2007","2/2/2007"))
data_s$Date <- as.Date(data_s$Date, format="%d/%m/%Y")
datetime <- paste(as.Date(data_s$Date), data_s$Time)
data_s$Datetime <- as.POSIXct(datetime)
with(data_s, {plot(Global_active_power~Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")})
dev.copy(png, file="plot2.png", height=480, width=480)